!*********************************************************************
!Contains definitions for DEBUG flags and namelists
!*********************************************************************

MODULE debugvar
  USE nrtype
  IMPLICIT NONE
  SAVE
! Following control debugging info:
  LOGICAL(LGT) DEBUG_AREA
  LOGICAL(LGT) DEBUG_EDGE_CONNECT
  LOGICAL(LGT) DEBUG_EIGENVECTORS
  LOGICAL(LGT) DEBUG_ELEMENT_E_FIELD
  LOGICAL(LGT) DEBUG_EDGEMAKE_VECTORS
  LOGICAL(LGT) DEBUG_EDGEMAKE_EDGES
  LOGICAL(LGT) DEBUG_FACEAREA
  LOGICAL(LGT) DEBUG_FACEMAKE_FACES
  LOGICAL(LGT) DEBUG_FACE_CONNECT
  LOGICAL(LGT) DEBUG_GW_PRE
  LOGICAL(LGT) DEBUG_MESHIN
  LOGICAL(LGT) DEBUG_NEWTON_RAPHSON
  LOGICAL(LGT) DEBUG_NUMBER_DOF
  LOGICAL(LGT) DEBUG_NODAL_E_FIELDS
  LOGICAL(LGT) DEBUG_SPARSE_MATVEC
  LOGICAL(LGT) DEBUG_SYSTEM_ELEMENTS
  LOGICAL(LGT) DEBUG_SYSTEM_MATRIX 
  LOGICAL(LGT) DEBUG_SOLVE_SPARSE
  LOGICAL(LGT) DEBUG_SKYLINE
  LOGICAL(LGT) DEBUG_TMAKE
  LOGICAL(LGT) DEBUG_VOLUME
  LOGICAL(LGT) DEBUG_WIJ
  LOGICAL(LGT) DEBUG_WRITE_MATRIX ! Causes the system matrix to be written out.
  LOGICAL(LGT) DEBUG_TD

  NAMELIST/DEBUGGING/DEBUG_AREA, &
       DEBUG_EIGENVECTORS, &
       DEBUG_ELEMENT_E_FIELD, &
       DEBUG_EDGE_CONNECT, &
       DEBUG_EDGEMAKE_VECTORS, & 
       DEBUG_EDGEMAKE_EDGES, &
       DEBUG_FACEMAKE_FACES, &
       DEBUG_FACEAREA, &
       DEBUG_FACE_CONNECT, & 
       DEBUG_GW_PRE, & 
       DEBUG_MESHIN, & 
       DEBUG_NEWTON_RAPHSON, &
       DEBUG_NODAL_E_FIELDS, &
       DEBUG_NUMBER_DOF, & 
       DEBUG_SPARSE_MATVEC, &
       DEBUG_SOLVE_SPARSE, &
       DEBUG_SKYLINE, &
       DEBUG_SYSTEM_ELEMENTS, & 
       DEBUG_SYSTEM_MATRIX, & 
       DEBUG_TMAKE, &
       DEBUG_VOLUME, & 
       DEBUG_WIJ, &
       DEBUG_WRITE_MATRIX, &
       DEBUG_TD

END MODULE debugvar
