load("HexaBasisFunction")$
load("BrickCoords")$
load("BrickSysmatUtils")$
load("OneBrick")$
load("eigen")$

D_onef_reffuns:remove_dep_vars(D_onef_efs)$
twof_reffuns:remove_dep_vars(twof_ffs)$

M_2:make_locmats(twof_reffuns, [get_verts(bricks[1], mesh_verts)])[1]$
P:make_proj_locmats(twof_reffuns, D_onef_reffuns, [get_verts(bricks[1], mesh_verts)])[1]$

noncommutative_dot_enter()$
C:(M_2^^-1).P$
noncommutative_dot_exit()$
