load("PyramidBasisFunction")$
load("SixPyrams")$
load("SysmatUtils")$

intg_pyr(fn):=integrate(integrate(integrate(fn,u1,0,1-u3),u2,0,1-u3),u3,0,1)$

make_locmat(BFlist, J):=make_locmat_generic(BFlist, J, intg_pyr)$
make_locmats(BFlist, pyr_verts):=makelist(
  make_locmat(subs_verts(BFlist, verts), subs_verts(J, verts)), verts, pyr_verts)$

/*vol: integrate(integrate(integrate(subs_verts(J, el_verts[1]),u1,0,1-u3),u2,0,1-u3),u3,0,1)$*/

make_tst_fns_u(fns):=makelist(subs_u(subs_grds_lam(fn)), fn, fns)$

tst_fns_u:make_tst_fns_u(onef_efs)$
D_tst_fns_u:make_tst_funs_u(D_onef_efs)$


/*locmat_oneform_mass:make_locmats(tst_fns_u, el_verts)$
locmat_oneform_stiffness:make_locmats(D_tst_fns_u, el_verts)$
*/

locmat_oneform_mass:make_locmats(make_tst_fns_u(p1_bfs), el_verts)$

