load("CommonSimplexStuff")$
load("tet_intgration_utils")$
load("SysmatUtils")$
load("BasisFunction")$

remove_dep_vars(BFs):=apply_repeatedly(vectorsimp, subst([lam4=1-lam1-lam2-lam3,0=[0,0,0]],BFs))$
gen_tetfns(BFs, tv):=subst(el_grd_lam_sublist(tv), BFs)$

tet_integrator(fn):= integrate(
  integrate(
    integrate(fn, lam3, 0, 1-lam1-lam2),
    lam2, 0, 1-lam1),
  lam1, 0, 1)$

make_locmat(BFlist, J):=make_locmat_generic(BFlist, J, tet_integrator)$

make_proj_locmat(BFlist_i, BFlist_j, J):=make_proj_locmat_generic(
  BFlist_i, BFlist_j, J, tet_integrator)$

make_locmats(BFlist, tets_verts):=makelist(
  make_locmat(express(gen_tetfns(BFlist, tv)), simplex_tetmat(tv)),
    tv, tets_verts)$

make_proj_locmats(BFlist_i, BFlist_j, tet_verts):=makelist(
  make_proj_locmat(
    express(gen_tetfns(BFlist_i, tv)),
    express(gen_tetfns(BFlist_j, tv)),
    simplex_tetmat(tv)),
  tv, tet_verts)$
  
test_locmats_TwoTets(BFlist):=(load("TwoTets.mac"),
  make_locmats(BFlist, makelist(get_verts(tet, mesh_verts), tet, tets)))$

test_proj_locmats_TwoTets(BFlist_i, BFlist_j):=(load("TwoTets.mac"),
  make_proj_locmats(BFlist_i, BFlist_j, makelist(get_verts(tet, mesh_verts), tet, tets)))$

test_locandglobmat_TwoTets(BFlist, dofmap):=block([lms:test_locmats_TwoTets(BFlist)],
  [lms, make_global_add_symm(lms, dofmap)])$

onef_1_mixed_bfs:remove_dep_vars(onef_efs_R1)$
D_onef_1_mixed_bfs:remove_dep_vars(D_onef_efs_R1)$
onef_2_mixed_bfs:remove_dep_vars(append(
    onef_efs_R1, onef_efs_G1, facetrips_to_flatlist(onef_ffs_R2)))$
D_onef_2_mixed_bfs:remove_dep_vars(append(
    D_onef_efs_R1, D_onef_efs_G1, facetrips_to_flatlist(D_onef_ffs_R2)))$
onef_2_bfs:remove_dep_vars(append(
    onef_efs_R1, onef_efs_G1, onef_efs_G2, facetrips_to_flatlist(onef_ffs_R2),
    facetrips_to_flatlist(onef_ffs_G2)))$
D_onef_2_bfs:remove_dep_vars(append(
    D_onef_efs_R1, D_onef_efs_G1, D_onef_efs_G2, facetrips_to_flatlist(D_onef_ffs_R2),
    facetrips_to_flatlist(D_onef_ffs_G2)))$
onef_3_mixed_bfs:remove_dep_vars(append(onef_efs_R1, onef_efs_G1, onef_efs_G2,
    facetrips_to_flatlist(onef_ffs_R2), facetrips_to_flatlist(onef_ffs_G2),
    facetrips_to_flatlist(onef_ffs_R3), onef_vfs_R3))$
D_onef_3_mixed_bfs:remove_dep_vars(append(D_onef_efs_R1, D_onef_efs_G1, D_onef_efs_G2,
    facetrips_to_flatlist(D_onef_ffs_R2), facetrips_to_flatlist(D_onef_ffs_G2),
    facetrips_to_flatlist(D_onef_ffs_R3), D_onef_vfs_R3))$
onef_4_mixed_bfs:remove_dep_vars(append(onef_efs_R1, onef_efs_G1, onef_efs_G2, onef_efs_G3,
    facetrips_to_flatlist(onef_ffs_R2),
    facetrips_to_flatlist(onef_ffs_G2), facetrips_to_flatlist(onef_ffs_R3),
    facetrips_to_flatlist(onef_ffs_G3), facetrips_to_flatlist(onef_ffs_R4),
    onef_vfs_R3, onef_vfs_G3, onef_vfs_R4))$
D_onef_4_mixed_bfs:remove_dep_vars(append(D_onef_efs_R1, D_onef_efs_G1,
    D_onef_efs_G2, D_onef_efs_G3,
    facetrips_to_flatlist(D_onef_ffs_R2),
    facetrips_to_flatlist(D_onef_ffs_G2), facetrips_to_flatlist(D_onef_ffs_R3),
    facetrips_to_flatlist(D_onef_ffs_G3), facetrips_to_flatlist(D_onef_ffs_R4),
    D_onef_vfs_R3, D_onef_vfs_G3, D_onef_vfs_R4))$
onef_4_bfs:remove_dep_vars(append(onef_efs_R1, onef_efs_G1, onef_efs_G2, onef_efs_G3, onef_efs_G4,
    facetrips_to_flatlist(onef_ffs_R2),
    facetrips_to_flatlist(onef_ffs_G2), facetrips_to_flatlist(onef_ffs_R3),
    facetrips_to_flatlist(onef_ffs_G3), facetrips_to_flatlist(onef_ffs_R4),
    facetrips_to_flatlist(onef_ffs_G4), onef_vfs_R3, onef_vfs_G3, onef_vfs_R4,
    onef_vfs_G4))$
D_onef_4_bfs:remove_dep_vars(append(
    D_onef_efs_R1, D_onef_efs_G1, D_onef_efs_G2, D_onef_efs_G3, D_onef_efs_G4,
    facetrips_to_flatlist(D_onef_ffs_R2),
    facetrips_to_flatlist(D_onef_ffs_G2), facetrips_to_flatlist(D_onef_ffs_R3),
    facetrips_to_flatlist(D_onef_ffs_G3), facetrips_to_flatlist(D_onef_ffs_R4),
    facetrips_to_flatlist(D_onef_ffs_G4), D_onef_vfs_R3, D_onef_vfs_G3, D_onef_vfs_R4,
    D_onef_vfs_G4))$
twof_1_mixed_bfs:remove_dep_vars(ffs)$

onef_dofmap_1_mixed:[[1, 2, 3, 4, 5, 6],
              [2, 3, 7, 6, 8, 9]]$
onef_dofmap_2_mixed:[[ 1,  3,  5,  7,  9, 11,  2,  4,  6,  8, 10, 12, 19, 21, 23, 25, 20,
       22, 24, 26],
       [ 3,  5, 13, 11, 15, 17,  4,  6, 14, 12, 16, 18, 23, 27, 29, 31, 24,
       28, 30, 32]]$
onef_dofmap_2:[[ 1,  4,  7, 10, 13, 16,  2,  5,  8, 11, 14, 17,  3,  6,  9, 12, 15,
       18, 28, 31, 34, 37, 29, 32, 35, 38, 30, 33, 36, 39],
       [ 4,  7, 19, 16, 22, 25,  5,  8, 20, 17, 23, 26,  6,  9, 21, 18, 24,
       27, 34, 40, 43, 46, 35, 41, 44, 47, 36, 42, 45, 48]]$
onef_dofmap_4:[[  1,   6,  11,  16,  21,  26,   2,   7,  12,  17,  22,  27,   3,
                 8,  13,  18,  23,  28,   4,   9,  14,  19,  24,  29,   5,  10,
                 15,  20,  25,  30,  46,  61,  76,  91,  47,  62,  77,  92,  48,
                 63,  78,  93,  49,  64,  79,  94,  50,  65,  80,  95,  51,  66,
                 81,  96,  52,  67,  82,  97,  53,  68,  83,  98,  54,  69,  84,
                 99,  55,  70,  85, 100,  56,  71,  86, 101,  57,  72,  87, 102,
                 58,  73,  88, 103,  59,  74,  89, 104,  60,  75,  90, 105, 151,
                 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165],
              [  6,  11,  31,  26,  36,  41,   7,  12,  32,  27,  37,  42,   8,	    
                13,  33,  28,  38,  43,   9,  14,  34,  29,  39,  44,  10,  15,	    
                35,  30,  40,  45,  76, 106, 121, 136,  77, 107, 122, 137,  78,	    
               108, 123, 138,  79, 109, 124, 139,  80, 110, 125, 140,  81, 111,	    
               126, 141,  82, 112, 127, 142,  83, 113, 128, 143,  84, 114, 129,	    
               144,  85, 115, 130, 145,  86, 116, 131, 146,  87, 117, 132, 147,	    
                88, 118, 133, 148,  89, 119, 134, 149,  90, 120, 135, 150, 166,	    
               167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180]]$
twof_dofmap:[[1, 2, 3, 4],
              [3, 5, 6, 7]]$
              

/*
load("good_tet_sysmat_values.mac")$

print( is(test_locandglobmat_TwoTets(onef_1_mixed_bfs, onef_dofmap_1_mixed)=good_onef_massmat_1_mixed))$
print( is(test_locandglobmat_TwoTets(D_onef_1_mixed_bfs, onef_dofmap_1_mixed)=good_onef_stiffmat_1_mixed))$
print( is(test_locandglobmat_TwoTets(onef_2_mixed_bfs, onef_dofmap_2_mixed)=good_onef_massmat_2_mixed))$
print( is(test_locandglobmat_TwoTets(D_onef_2_mixed_bfs, onef_dofmap_2_mixed)=good_onef_stiffmat_2_mixed))$
print( is(test_locandglobmat_TwoTets(onef_2_bfs, onef_dofmap_2)=good_onef_massmat_2))$
print( is(test_locandglobmat_TwoTets(D_onef_2_bfs, onef_dofmap_2)=good_onef_stiffmat_2))$
print( is(test_locandglobmat_TwoTets(onef_4_bfs, onef_dofmap_4)=good_onef_massmat_4))$
print( is(test_locandglobmat_TwoTets(D_onef_4_bfs, onef_dofmap_4)=good_onef_stiffmat_4))$
print( is(TwoTets(D_onef_4_bfs, onef_dofmap_4)=good_onef_stiffmat_4))
print( is(test_proj_locmats_TwoTets(twof_1_mixed_bfs, D_onef_1_mixed_bfs)=good_twof_1_mixed_D_onef_1_mixed_projmat))$
print( is(test_proj_locmats_TwoTets(onef_1_mixed_bfs, twof_1_mixed_bfs)=good_onef_1_mixed_twof_1_mixed_projmat))$

*/