load("test_sysmats")$
r0:[-1/3, -1/6, -1/3]$ /* Should be in tets[2] at lamda = [1/3,1/6,1/6,1/3] */
basis_set: onef_1_mixed_bfs$
point_match_fun:lambda([r], [0,0,1])$
dofmap:onef_dofmap_1_mixed$

local_point_RHS(tet_verts, basis_set, proj_fun, r0):=block(
  [verts:tet_verts, lam:ev_lam(el_lam(tet_verts), r0), tmp],
  if not (pt_in_tet(tet_verts, r0)) then (makelist(0,i,basis_set))
  else (
    tmp:map(lambda([bf], bf_gen_tet(tet_verts, bf)(lam).proj_fun(r0)),
      basis_set),
    ev(tmp)
    ))$

loc_point_RHSs: map(lambda([tet],
    matrix(local_point_RHS(get_verts(tet, mesh_verts), basis_set, point_match_fun, r0))),
  tets)$

glob_point_RHS: make_global(loc_point_RHSs, "+", [[1], [1]], dofmap)$