load("CommonSimplexStuff.mac")$
load("BasisFunction.mac")$
onef_refval(BF, lam):=block([grd_lam:[[1,0,0,0],
                            [0,1,0,0],
                            [0,0,1,0],
                            [0,0,0,1]]],
                            bf:ev(to_var_list(BF), grd_lam:ev(grd_lam)))$
make_refval_list(BFs, reffun, lams):=map(
  lambda([BF], map(lambda([lam], reffun(BF, lam)), lams)),
               BFs)$

twof_refval(BF, lam):=block([conv_vecs:[[ 1.,  0.,  0.,  0.,  0.,  0.],
                                        [ 0.,  1.,  0.,  0.,  0.,  0.],
                                        [ 0.,  0.,  1.,  0.,  0.,  0.],
                                        [ 0.,  0.,  0.,  1.,  0.,  0.],
                                        [ 0.,  0.,  0.,  0.,  1.,  0.],
                                        [ 0.,  0.,  0.,  0.,  0.,  1.]],
                                        BF_subbed],
  BF_subbed:to_var_list(subst([grad(lam1)~grad(lam2)=''conv_vecs[1],
      grad(lam1)~grad(lam3)=''conv_vecs[2],
      grad(lam1)~grad(lam4)=''conv_vecs[3],
      grad(lam2)~grad(lam3)=''conv_vecs[4],
      grad(lam2)~grad(lam4)=''conv_vecs[5],
      grad(lam3)~grad(lam4)=''conv_vecs[6]], BF)),
  if BF_subbed = 0 then ([0,0,0,0,0,0]) else (BF_subbed))$

onef_efs_R1_refvals:make_refval_list(onef_efs_R1, onef_refval, lams)$
onef_efs_G1_refvals:make_refval_list(onef_efs_G1, onef_refval, lams)$
onef_efs_G2_refvals:make_refval_list(onef_efs_G2, onef_refval, lams)$
onef_efs_G3_refvals:make_refval_list(onef_efs_G3, onef_refval, lams)$
onef_efs_G4_refvals:make_refval_list(onef_efs_G4, onef_refval, lams)$
onef_ffs_R2_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_R2),
                                     onef_refval, lams)$
onef_ffs_R3_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_R3),
                                     onef_refval, lams)$
onef_ffs_R4_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_R4),
                                     onef_refval, lams)$
onef_ffs_G2_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_G2),
                                     onef_refval, lams) $
onef_ffs_G3_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_G3),
                                     onef_refval, lams) $
onef_ffs_G4_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_G4),
                                     onef_refval, lams) $

onef_vfs_R3_refvals:make_refval_list(onef_vfs_R3, onef_refval, lams)$
onef_vfs_R4_refvals:make_refval_list(onef_vfs_R4, onef_refval, lams)$

D_onef_efs_R1_refvals:make_refval_list(D_onef_efs_R1, twof_refval, lams)$
D_onef_efs_G1_refvals:make_refval_list(D_onef_efs_G1, twof_refval, lams)$
D_onef_efs_G2_refvals:make_refval_list(D_onef_efs_G2, twof_refval, lams)$
D_onef_efs_G3_refvals:make_refval_list(D_onef_efs_G3, twof_refval, lams)$
D_onef_efs_G4_refvals:make_refval_list(D_onef_efs_G4, twof_refval, lams)$
D_onef_ffs_R2_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_R2),
                                     twof_refval, lams)$
D_onef_ffs_R3_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_R3),
                                     twof_refval, lams)$
D_onef_ffs_R4_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_R4),
                                     twof_refval, lams)$
D_onef_ffs_G2_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_G2),
                                     twof_refval, lams)$                                   
D_onef_ffs_G3_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_G3),
                                     twof_refval, lams)$                                   
D_onef_ffs_G4_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_G4),
                                     twof_refval, lams)$                                   

D_onef_vfs_R3_refvals:make_refval_list(D_onef_vfs_R3, twof_refval, lams)$
D_onef_vfs_R4_refvals:make_refval_list(D_onef_vfs_R4, twof_refval, lams)$

onef_efs_G5_refvals:make_refval_list(onef_efs_G5, onef_refval, lams)$
onef_ffs_G5_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_G5),
                                     onef_refval, lams) $
onef_vfs_G3_refvals:make_refval_list(onef_vfs_G3, onef_refval, lams)$
onef_vfs_G4_refvals:make_refval_list(onef_vfs_G4, onef_refval, lams)$
onef_vfs_G5_refvals:make_refval_list(onef_vfs_G5, onef_refval, lams)$

onef_ffs_R5_refvals:make_refval_list(facetrips_to_flatlist(onef_ffs_R5),
                                     onef_refval, lams)$
onef_vfs_R5_refvals:make_refval_list(onef_vfs_R5, onef_refval, lams)$

D_onef_efs_G5_refvals:make_refval_list(D_onef_efs_G5, twof_refval, lams)$
D_onef_ffs_G5_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_G5),
                                     twof_refval, lams)$
D_onef_vfs_G3_refvals:make_refval_list(D_onef_vfs_G3, onef_refval, lams)$
D_onef_vfs_G4_refvals:make_refval_list(D_onef_vfs_G4, onef_refval, lams)$
D_onef_vfs_G5_refvals:make_refval_list(D_onef_vfs_G5, onef_refval, lams)$
D_onef_ffs_R5_refvals:make_refval_list(facetrips_to_flatlist(D_onef_ffs_R5),
                                     twof_refval, lams)$                                   
D_onef_vfs_R5_refvals:make_refval_list(D_onef_vfs_R5, twof_refval, lams)$