load("PyramidBasisFunction")$
load("PyramidRefvalUtils")$

gen_baseedge_interp_fns(base_interp):=apply(append, makelist(makelist(
      shift_fn_edge(ifun, i), i, onef_baseedge_fn_i),
    ifun, base_interp))$

gen_apexedge_interp_fns(apex_interp):=apply(append, makelist(makelist(
      shift_fn_edge(ifun, i), i, onef_apexedge_fn_i),
    ifun, apex_interp))$

baseedge_interp_fns:gen_baseedge_interp_fns(p1_onef_base_edge_interp_fns)$
D_baseedge_interp_fns:post_crl_simplify(map("grad", baseedge_interp_fns))$
apexedge_interp_fns:gen_apexedge_interp_fns(p1_onef_apex_edge_interp_fns)$
D_apexedge_interp_fns:post_crl_simplify(map("grad", apexedge_interp_fns))$

apexface_interp_fns:block([revlist:[2,3],
  /* revlist contains face numbers that have their edge senses reversed as
  compared to the senses required for inter-element continuity */ 
  i0_bfs:apply(append, makelist(
      makelist(shift_fn_edge(int_fn, i),
        i, onef_apexface_fn_i0_i),
      int_fn, p1_onef_apex_facei0_interp_fns)),
  i1_bfs:apply(append, makelist(
      makelist(shift_fn_edge(int_fn, i),
        i, onef_apexface_fn_i1_i),
      int_fn, p1_onef_apex_facei1_interp_fns))],
  append(makelist(
      if not member(mod(i,4), revlist) then i0_bfs[i] else i1_bfs[i],
      i, 1, length(i0_bfs)),
    makelist(
      if not member(mod(i,4), revlist) then i1_bfs[i] else i0_bfs[i],
      i, 1, length(i0_bfs)))
    )$

D_apexface_interp_fns:post_crl_simplify(map("grad", apexface_interp_fns))$

baseface_interp_fns:apply(append,
    makelist(
      makelist(shift_fn_edge(int_fn, i), int_fn, p1_onef_base_face_interp_fns),
      i, onef_baseface_fn_i))$
D_baseface_interp_fns:post_crl_simplify(map("grad", baseface_interp_fns))$

basevol_interp_fns:apply(append,
  makelist(makelist(
      shift_fn_edge(int_fn, i), i, onef_volbase_fn_i),
    int_fn, p1_onef_base_vol_interp_fns))$
D_basevol_interp_fns:post_crl_simplify(map("grad", basevol_interp_fns))$

apexedge_interp_vals:num_vals(to_lamlist(apexedge_interp_fns), test_pyr_lams)$
D_apexedge_interp_vals:num_vals(onef_fun_refvals(D_apexedge_interp_fns), test_pyr_lams)$
baseedge_interp_vals:num_vals(to_lamlist(baseedge_interp_fns), test_pyr_lams)$
D_baseedge_interp_vals:num_vals(onef_fun_refvals(D_baseedge_interp_fns), test_pyr_lams)$

apexface_interp_vals:num_vals(to_lamlist(apexface_interp_fns), test_pyr_lams)$
D_apexface_interp_vals:num_vals(onef_fun_refvals(D_apexface_interp_fns), test_pyr_lams)$
baseface_interp_vals:num_vals(to_lamlist(baseface_interp_fns), test_pyr_lams)$
D_baseface_interp_vals:num_vals(onef_fun_refvals(D_baseface_interp_fns), test_pyr_lams)$
basevol_interp_vals:num_vals(to_lamlist(basevol_interp_fns), test_pyr_lams)$
D_basevol_interp_vals:num_vals(onef_fun_refvals(D_basevol_interp_fns), test_pyr_lams)$
