load("test_BF_physvals")$
load("eigen")$

get_normal(fv):=block([b:fv[2]-fv[1],c:fv[3]-fv[1]], uvect(express(b~c)))$
get_tang_comp(n, val):=express(-n~(n~val))$

tri_norms:makelist(get_normal(get_verts(local_facenodes[i], mesh_verts)),i,1,length(tri_lams))$
tri_tang_physvals:makelist(makelist(makelist(get_tang_comp(tri_norms[i], val), val, lamvals),
  lamvals, physvals_from_BF_list(tv, onef_efs_R1, tri_lams[i])), i, 1, length(tri_lams))$
tri_tang_subset:makelist(makelist(
    tri_tang_physvals[local_faceno][i], i, local_faceedges[local_faceno]),
  local_faceno,1, length(local_faceedges))$